#!/usr/bin/env bash
#
while IFS=: read -r username password userid groupid userinfo homedir shell
do
  echo "The user $username is part of the group $groupid, lives in $homedir and uses $shell. The user ID's place is protected by the passcode $password, more info about the user here: $userinfo"
done < /etc/passwd
