#!/usr/bin/env bash
#
PIDFILE="/var/run/myscript.pid"
echo $$ > "$PIDFILE"
ss(){
  echo "I hate the kill command"
  rm -f $PIDFILE
  exit 0
}
s(){
  echo "Y U no love me?!"
}
term 'ss' SIGQUIT SIGTERM
term 's' SIGINT
while true
do 
  echo "To infinity and beyond"
done
